source "https://rubygems.org" # gems.ruby-china.com

gem 'jekyll-rtd-theme', '~> 2.0', '>= 2.0.10'

gem "github-pages", group: :jekyll_plugins


group :jekyll_plugins do
    gem "jekyll-default-layout"
    gem "jekyll-readme-index"
    gem "jekyll-github-metadata"
    gem "jekyll-titles-from-headings"
    gem "jemoji"
    gem "jekyll-avatar"
    gem "jekyll-mentions"
    gem "jekyll-relative-links"
  end
  
